#+title: SQL Lesson 10: Queries with aggregates

SQL also supports the use of aggregative expressions (or functions) that allows to summarize information about a group of data. As an example aggregate functions can be used to aswer the questions like, "How many movies has Pixar produced?", of "What is the highest grossing Pixar film each year?"

Select query with aggregate functions over all rows:
#+BEGIN_SRC sql
SELECT AGG_FUNC(column_or_expression) AS aggregate_description, …
FROM mytable
WHERE constraint_expression;
#+END_SRC

Without specifying a group, each aggregate function is going to run on the whole set of result rows and return a single value. And like normal expressions, giving your aggregate functions an alias ensures that the results will be easier to read and process

* Common aggregate functions:

| Function      | Description                                                                                     |
|---------------+-------------------------------------------------------------------------------------------------|
| COUNT(*)      | A common function used to counts the number of rows in the group if no column name is specified |
| COUNT(column) | Count the number of rows in the group with non-NULL values in the specified column              |
| MIN(column)   | Finds the smallest numerical value in the specified column for all rows in the group.           |
| MAX(column)   | Finds the largest numerical value in the specified column for all rows in the group.            |
| AVG(column)   | Finds the average numerical value in the specified column for all rows in the group             |
| SUM(column)   | Finds the sum of all numerical values in the specified column for the rows in the group         |

* Grouped aggregate functions

In addition to aggregating across all the rows, you can instead apply the aggregate functions to individual groups of data within that group (ie. box office sales for Comedies vs Action movies).
This would then create as many results as there are unique groups defined as by the GROUP BY clause.

#+BEGIN_SRC sql
SELECT AGG_FUNC(column_or_expression) AS aggregate_description, …
FROM mytable
WHERE constraint_expression
GROUP BY column;
#+END_SRC

The GROUP BY clause works by grouping rows that have the same value in the column specified.
